DROP TABLE IF EXISTS Action CASCADE;
DROP TABLE IF EXISTS Circle CASCADE;
DROP TABLE IF EXISTS Hiddenitem CASCADE;
DROP TABLE IF EXISTS Hunter CASCADE;
DROP TABLE IF EXISTS Immersion CASCADE;
DROP TABLE IF EXISTS Monster CASCADE;
DROP TABLE IF EXISTS Plant CASCADE;
DROP TABLE IF EXISTS Shelter CASCADE;
DROP TYPE IF EXISTS actions;